export const lightTheme = {
    border: 'black',
    secondaryBorder: '#ced4da',
    body: '#FFF',
    text: '#363537',
    toggleBorder: 'black',
    background: '#FFF',
    hover: 'rgba(0,0,0,0.15)',
    recipetext: '#737373',
    divider: '#ebebeb',
    divide: '#ebebeb',
    closeModal: 'black',
    tableStyle: '#363537',
    close: 'black',
    timerBtns1: "#8b95a5",
    timerBtns2: "#8b95a5",
}

export const darkTheme = {
    border: '#FFF',
    secondaryBorder: 'rgba(0, 0, 0, 0.125)',
    body: '#363537',
    text: '#FAFAFA',
    toggleBorder: 'white',
    background: '#737373',
    hover: 'rgba(255,255,255,0.5)',
    recipetext: 'lightgray',
    divider: '#8b95a5',
    divide: '#8b95a5',
    closeModal: 'white',
    tableStyle: 'lightgray',
    close: 'white',
    timerBtns1: "lightgray",
    timerBtns2: "#929292",
}